### ISSUE TITLE
 The provided "cucumber-JSON" reporter does not exist. Check that you have specified the report format correctly.

### ISSUE THREAD

**Issue by RemigiusL** [hdorgeval/testcafe-reporter-cucumber-json#11]
Hi @hdorgeval,

After installing your Cucumber JSON TestCafe Reporter (beta) npm package. I'm trying to get the HTML report using your given comment **testcafe chrome ./path-to-tests/*(.js|.testcafe|.ts) --reporter cucumber-json:reports/report.json --reporter-app-name='My App' --reporter-app-version='x.y.z'** but not able to get the report.
It says `ERROR: The provided "cucumber-JSON" reporter does not exist. Check that you have specified the report format correctly.`

Also, I'm new to tastcafe, So, could you pls help me out? `which file need to execute /path-to-tests/*.js` ?

**Comment by hdorgeval** [comment]
Hi @RemigiusL , the error message you give me tells that TestCafe cannot find a folder named `testcafe-reporter-cucumber-JSON`. 

TestCafe dynamically loads reporters based on their names. For example, when you set on the command line `--reporter foo`, TestCafe looks for a folder named `testcafe-reporter-foo` in the `node_modules` folder.

The only explanation for such an error is that you have set the command line option like `--reporter FOO` instead of `--reporter foo`: TestCafe searches for a folder in `node_modules` called `testcafe-reporter-FOO` which is not the same as `testcafe-reporter-foo`.

So could you check that the command line option is naming the reporter in lower case and not like `cucumber-JSON` (it should be `cucumber-json`).

**Comment by RemigiusL** [comment]
> Hi @RemigiusL , the error message you give me tells that TestCafe cannot find a folder named `testcafe-reporter-cucumber-JSON`.
> 
> TestCafe dynamically loads reporters based on their names. For example, when you set on the command line `--reporter foo`, TestCafe looks for a folder named `testcafe-reporter-foo` in the `node_modules` folder.
> 
> The only explanation for such an error is that you have set the command line option like `--reporter FOO` instead of `--reporter foo`: TestCafe searches for a folder in `node_modules` called `testcafe-reporter-FOO` which is not the same as `testcafe-reporter-foo`.
> 
> So could you check that the command line option is naming the reporter in lower case and not like `cucumber-JSON` (it should be `cucumber-json`).
